travis:
  secure:
    BINSTAR_TOKEN: bg/N5qeLB1Umnr3CAMAqQsyZUoixaLInxdR5qudy8m9T45vu4wgNPzVjxbw7azMdeTQIOj6bvLLYIm1ckEG0B8w+qtO0bK6KnmUOTm4DnSzFtq4eKe41aNG1mn6y8CWi24lQetYvLj04zhuEXT4g1vDZU72yqfztF5G2RQy29XgoYxSQI6fvivWk/2eUga4KtqBzh7R4IbQNMgPDqoyl9b0/1XZjWFALF/Jq+JWWVVyhW0/aiUq8fZI1x8C40nWZiqhn/gPrF4idfFPgs83TY3bhOBG3v0BLgNWLVMci4sPrDgHrx4nEQDQ3mHX6ZOevDoD85hrGQcU9VaAga8O9uEMb9FPk3Y3+Z6dshX+bn17JG/IvJ8O06iTgEMqHVkYDAradu+9SyODdR+0n5Ukh7g5Kf/I7UWvMYr5gezYrdSIyGJGZngfDc3ypIMg6k0A1Ha7NzxX/tpeEd5UV0csfGYbBbRJFaIVebfY5eze3zOWzkmVKFHAzr+bY7cZFcEEThair54W2N9ca+7gOuiYtu3v+rPaPF0JJB8Kf8jOSgx++gDILWCrcIs4HjrcUWU5ZYEBuuaHNJTkQYooa3W7r1phdyRZuFy77Fh463FjDrinxkddEhLRdjyFCXimi0J2J0uF/AeXhQmwhLGzNRYSxoMo1dmOTrIt4Xf8h5/1M3Jo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
